#!/usr/bin/env bash
# slam - simple command wrapper for SLAM project

set -e

CMD=$1
shift || true  # remove first argument, rest go in $@

case "$CMD" in
  docker_build)
    docker build -f docker/Dockerfile -t ros-gpio .
    ;;
  build)
    docker run -it --rm \
    --device /dev/gpiomem \
    --privileged \
    -v $(pwd)/src:/app/src \
    -v $(pwd)/assets/figures:/app/figures \
    -w /app/src \
    -p 8765:8765 \
    ros-gpio \
    bash -c "source /opt/ros/humble/setup.bash && colcon build"
    ;;
  run)
    docker run -it --rm \
    --device /dev/gpiomem \
    --privileged \
    -v $(pwd)/src:/app/src \
    -v $(pwd)/assets/figures:/app/figures \
    -w /app/src \
    -p 8765:8765 \
    -e MPU_BUS_ADR=$MPU_BUS_ADR \
    ros-gpio \
    bash -c "source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 launch slam_launch slam.launch.py"
    ;;
  foxglove)
    docker exec -it ros-gpio ros2 launch foxglove_bridge foxglove_bridge.launch.xml
    ;;
  setup_i2c)
    chmod +x ./scripts/setup_i2c.sh && ./scripts/setup_i2c.sh 
    ;;
  *)
    echo "Usage: slam {build|run|foxglove|setup_i2c}"
    exit 1
    ;;
esac
